@host = http://192.168.49.2
@port = 30282
@baseUrl = {{host}}:{{port}}
@contentType = application/json

###
GET {{baseUrl}}/posts

###
POST {{baseUrl}}/posts
Content-Type: {{contentType}}

{
    "title": "My Post"
}