@host = http://192.168.49.2
@port = 30282
@baseUrl = {{host}}:{{port}}
@contentType = application/json

###
GET {{baseUrl}}/posts/1/comments

###
POST {{baseUrl}}/posts/1/comments
Content-Type: {{contentType}}

{
    "title": "My Post"
}